print("Creating a text file with the write<> method.\n")
text_file = open("write_it.txt", "w")
text_file.write("Line 1\n")
text_file.write("This is line 2\n")
text_file.close()
print("Reading the newly created file.")
text_file = open("write_it.txt", "r")
whole_thing = text_file.read()
print(whole_thing, end='')
text_file.close()
print("and that would make this the Third line.\n\n")
print("Creating a text file with teh writelines<> mehtod.\n")
text_file = open("write_it.txt", "w")
lines = ["Line 1\n", "This is line 2\n", "That makes this line 3\n"]
text_file.writelines(lines)
text_file.close()
print("Reading the newly created file.")
text_file = open("write_it.txt", "r")
while_thing = text_file.read()
print(while_thing)
