print("Opening and closing the file.\n\nReading characters form the file.")
text_file = open("read_it.txt", "r")
print(text_file.read(1))
print(text_file.read(5))
print("Reading the entire file at once.")
whole_thing = text_file.read()
print(whole_thing)
text_file = open("read_it.txt", "r")
print("\nReading characters from a line")
print(text_file.readline(1))
print(text_file.readline(5))
text_file = open("read_it.txt", "r")
print("\nReading one line at a time.")
print(text_file.readline())
print(text_file.readline())
print(text_file.readline())
text_file = open("read_it.txt", "r")
print("\nReading the entire file into a list.")
lines = text_file.readlines()
print(lines)
print(len(lines))
print(lines[0])
print(lines[1])
print(lines[2])
print("\nLooping through the file, line by line.")
text_file = open("read_it.txt", "r")
for line in text_file:
    print(line)
text_file.close()
